"""deepen mastery knowledge variant cheating

Revision ID: 1991c3a0b954
Revises: 9eddda5abcc8
Create Date: 2026-10-04 10:50:19.097153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1991c3a0b954'
down_revision: Union[str, Sequence[str], None] = '9eddda5abcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('p_init', sa.Float(), nullable=False),
    sa.Column('p_transit', sa.Float(), nullable=False),
    sa.Column('p_slip', sa.Float(), nullable=False),
    sa.Column('p_guess', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_points_code'), 'knowledge_points', ['code'], unique=True)
    op.create_table('mastery_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('observed', sa.Boolean(), nullable=False),
    sa.Column('mastery_before', sa.Float(), nullable=False),
    sa.Column('mastery_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_point_id', 'source', 'submission_id', name='uq_mastery_event_once')
    )
    op.create_index(op.f('ix_mastery_events_knowledge_point_id'), 'mastery_events', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_mastery_events_submission_id'), 'mastery_events', ['submission_id'], unique=False)
    op.create_index(op.f('ix_mastery_events_user_id'), 'mastery_events', ['user_id'], unique=False)
    op.create_table('student_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_point_id', name='uq_mastery_user_kp')
    )
    op.create_index(op.f('ix_student_mastery_knowledge_point_id'), 'student_mastery', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_student_mastery_user_id'), 'student_mastery', ['user_id'], unique=False)
    op.create_table('assignment_knowledge_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'knowledge_point_id', name='uq_akp')
    )
    op.create_index(op.f('ix_assignment_knowledge_points_assignment_id'), 'assignment_knowledge_points', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_knowledge_points_knowledge_point_id'), 'assignment_knowledge_points', ['knowledge_point_id'], unique=False)
    op.add_column('assignments', sa.Column('kind', sa.String(length=16), server_default='formal', nullable=False))
    op.add_column('assignments', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assignments_assigned_user_id'), 'assignments', ['assigned_user_id'], unique=False)
    op.add_column('cheating_reports', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('misconceptions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('misconceptions', sa.Column('knowledge_point_id', sa.Integer(), nullable=True))
    op.add_column('misconceptions', sa.Column('evidence_validated', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('misconceptions', sa.Column('status', sa.String(length=16), server_default='open', nullable=False))
    op.add_column('misconceptions', sa.Column('overcome_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_misconceptions_knowledge_point_id'), 'misconceptions', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_misconceptions_user_id'), 'misconceptions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'misconceptions', 'knowledge_points', ['knowledge_point_id'], ['id'], ondelete='SET NULL')
    op.add_column('variant_exercises', sa.Column('origin_misconception_id', sa.Integer(), nullable=True))
    op.add_column('variant_exercises', sa.Column('practice_assignment_id', sa.Integer(), nullable=True))
    op.add_column('variant_exercises', sa.Column('difficulty', sa.String(length=16), server_default='easy', nullable=False))
    op.create_index(op.f('ix_variant_exercises_origin_misconception_id'), 'variant_exercises', ['origin_misconception_id'], unique=False)
    op.create_index(op.f('ix_variant_exercises_practice_assignment_id'), 'variant_exercises', ['practice_assignment_id'], unique=False)
    op.create_foreign_key(None, 'variant_exercises', 'assignments', ['practice_assignment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'variant_exercises', 'misconceptions', ['origin_misconception_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variant_exercises', type_='foreignkey')
    op.drop_constraint(None, 'variant_exercises', type_='foreignkey')
    op.drop_index(op.f('ix_variant_exercises_practice_assignment_id'), table_name='variant_exercises')
    op.drop_index(op.f('ix_variant_exercises_origin_misconception_id'), table_name='variant_exercises')
    op.drop_column('variant_exercises', 'difficulty')
    op.drop_column('variant_exercises', 'practice_assignment_id')
    op.drop_column('variant_exercises', 'origin_misconception_id')
    op.drop_constraint(None, 'misconceptions', type_='foreignkey')
    op.drop_index(op.f('ix_misconceptions_user_id'), table_name='misconceptions')
    op.drop_index(op.f('ix_misconceptions_knowledge_point_id'), table_name='misconceptions')
    op.drop_column('misconceptions', 'overcome_at')
    op.drop_column('misconceptions', 'status')
    op.drop_column('misconceptions', 'evidence_validated')
    op.drop_column('misconceptions', 'knowledge_point_id')
    op.drop_column('misconceptions', 'user_id')
    op.drop_column('cheating_reports', 'meta')
    op.drop_index(op.f('ix_assignments_assigned_user_id'), table_name='assignments')
    op.drop_column('assignments', 'assigned_user_id')
    op.drop_column('assignments', 'kind')
    op.drop_index(op.f('ix_assignment_knowledge_points_knowledge_point_id'), table_name='assignment_knowledge_points')
    op.drop_index(op.f('ix_assignment_knowledge_points_assignment_id'), table_name='assignment_knowledge_points')
    op.drop_table('assignment_knowledge_points')
    op.drop_index(op.f('ix_student_mastery_user_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_knowledge_point_id'), table_name='student_mastery')
    op.drop_table('student_mastery')
    op.drop_index(op.f('ix_mastery_events_user_id'), table_name='mastery_events')
    op.drop_index(op.f('ix_mastery_events_submission_id'), table_name='mastery_events')
    op.drop_index(op.f('ix_mastery_events_knowledge_point_id'), table_name='mastery_events')
    op.drop_table('mastery_events')
    op.drop_index(op.f('ix_knowledge_points_code'), table_name='knowledge_points')
    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
