"""add cheating_reports table

Revision ID: 2b52e9c81af5
Revises: 00146cf951e3
Create Date: 2026-09-26 12:24:10.335819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b52e9c81af5'
down_revision: Union[str, Sequence[str], None] = '00146cf951e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheating_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheating_reports_student_id'), 'cheating_reports', ['student_id'], unique=False)
    op.create_index(op.f('ix_cheating_reports_submission_id'), 'cheating_reports', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cheating_reports_submission_id'), table_name='cheating_reports')
    op.drop_index(op.f('ix_cheating_reports_student_id'), table_name='cheating_reports')
    op.drop_table('cheating_reports')
    # ### end Alembic commands ###
