"""add appeals table

Revision ID: 5581c0563bc1
Revises: 8fb5bfe23913
Create Date: 2026-09-26 11:02:13.956422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5581c0563bc1'
down_revision: Union[str, Sequence[str], None] = '8fb5bfe23913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('new_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeals_student_id'), 'appeals', ['student_id'], unique=False)
    op.create_index(op.f('ix_appeals_submission_id'), 'appeals', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_submission_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_student_id'), table_name='appeals')
    op.drop_table('appeals')
    # ### end Alembic commands ###
