"""add assignment course_id

Revision ID: b2e49328f9da
Revises: 637958ad7a97
Create Date: 2026-09-26 10:43:27.526992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e49328f9da'
down_revision: Union[str, Sequence[str], None] = '637958ad7a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assignments_course_id'), 'assignments', ['course_id'], unique=False)
    op.create_foreign_key(None, 'assignments', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_course_id'), table_name='assignments')
    op.drop_column('assignments', 'course_id')
    # ### end Alembic commands ###
