"""add misconceptions table

Revision ID: ce80550c11e8
Revises: 1fbc10027672
Create Date: 2026-09-26 09:23:07.118823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce80550c11e8'
down_revision: Union[str, Sequence[str], None] = '1fbc10027672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('misconception_type', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('knowledge_point', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconceptions_submission_id'), 'misconceptions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_misconceptions_submission_id'), table_name='misconceptions')
    op.drop_table('misconceptions')
    # ### end Alembic commands ###
