"""add variant_exercises table

Revision ID: fd5a37cc14f3
Revises: ce80550c11e8
Create Date: 2026-09-26 09:42:02.136854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5a37cc14f3'
down_revision: Union[str, Sequence[str], None] = 'ce80550c11e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cases', sa.JSON(), nullable=True),
    sa.Column('scoring_points', sa.JSON(), nullable=True),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_exercises_submission_id'), 'variant_exercises', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_exercises_submission_id'), table_name='variant_exercises')
    op.drop_table('variant_exercises')
    # ### end Alembic commands ###
